<?php

namespace App\Support;

use Illuminate\Support\Collection;

class PurchaseOrderStore
{
    private const SESSION_KEY = 'purchase_orders';

    public function all(): Collection
    {
        if (!session()->has(self::SESSION_KEY)) {
            session()->put(self::SESSION_KEY, $this->seed());
        }

        return collect(session()->get(self::SESSION_KEY, []));
    }

    public function find(string $id): ?array
    {
        return $this->all()->firstWhere('id', $id);
    }

    public function save(array $po): void
    {
        $orders = $this->all()->keyBy('id');
        $po['total'] = array_sum(array_map(
            fn($item) => (float)($item['quantity'] ?? 0) * (float)($item['unit_price'] ?? 0),
            $po['items'] ?? []
        ));
        $orders->put($po['id'], $po);
        session()->put(self::SESSION_KEY, $orders->values()->all());
    }

    public function delete(string $id): void
    {
        $orders = $this->all()->filter(fn($po) => $po['id'] !== $id);
        session()->put(self::SESSION_KEY, $orders->values()->all());
    }

    public function seed(): array
    {
        return [
            [
                'id' => 'po-001',
                'po_number' => '4500062472',
                'po_date' => '2026-06-24',
                'sla_date' => '2026-07-22',
                'client_name' => 'Star Media Group Berhad',
                'client_type' => 'Private',
                'category' => 'Trophies & Awards',
                'contact' => 'procurement@starmedia.com.my',
                'your_ref' => 'QT-180',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 50,
                'amount_paid' => 10137.00,
                'items' => [
                    ['id' => 'i-001-1', 'description' => 'Gold ESG Trophy', 'delivery_date' => '2026-07-22', 'quantity' => 32, 'unit' => 'pcs', 'unit_price' => 308.00],
                    ['id' => 'i-001-2', 'description' => 'Silver ESG Trophy', 'delivery_date' => '2026-07-22', 'quantity' => 31, 'unit' => 'pcs', 'unit_price' => 308.00],
                    ['id' => 'i-001-3', 'description' => 'Tall ESG Trophy', 'delivery_date' => '2026-07-22', 'quantity' => 2, 'unit' => 'pcs', 'unit_price' => 385.00],
                    ['id' => 'i-001-4', 'description' => 'Delivery', 'delivery_date' => '2026-07-22', 'quantity' => 1, 'unit' => 'unit', 'unit_price' => 100.00],
                ],
                'total' => 20274.00,
                'source' => 'pdf',
                'created_at' => '2026-06-24T09:00:00',
            ],
            [
                'id' => 'po-002',
                'po_number' => 'PO-2026-0085',
                'po_date' => '2026-04-10',
                'sla_date' => '2026-05-08',
                'client_name' => 'Jabatan Perdana Menteri',
                'client_type' => 'Government',
                'category' => 'Engraved Signage',
                'contact' => 'procurement.jpm@gov.my',
                'your_ref' => null,
                'currency' => 'MYR',
                'payment_term' => 'full_on_completion',
                'deposit_percent' => 0,
                'amount_paid' => 18500.00,
                'items' => [
                    ['id' => 'i-002-1', 'description' => 'Brass Name Plaque (A4)', 'delivery_date' => '2026-05-08', 'quantity' => 50, 'unit' => 'pcs', 'unit_price' => 220.00],
                    ['id' => 'i-002-2', 'description' => 'Acrylic Directional Sign', 'delivery_date' => '2026-05-08', 'quantity' => 20, 'unit' => 'pcs', 'unit_price' => 350.00],
                    ['id' => 'i-002-3', 'description' => 'Delivery & Installation', 'delivery_date' => '2026-05-08', 'quantity' => 1, 'unit' => 'set', 'unit_price' => 500.00],
                ],
                'total' => 18500.00,
                'source' => 'manual',
                'created_at' => '2026-04-10T10:30:00',
            ],
            [
                'id' => 'po-003',
                'po_number' => 'PO-2026-0091',
                'po_date' => '2026-04-22',
                'sla_date' => '2026-05-20',
                'client_name' => 'Petronas Dagangan Berhad',
                'client_type' => 'Private',
                'category' => 'Event Décor',
                'contact' => 'events@petronas.com.my',
                'your_ref' => 'QT-192',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 50,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-003-1', 'description' => 'Custom Event Backdrop 3x6m', 'delivery_date' => '2026-05-20', 'quantity' => 2, 'unit' => 'pcs', 'unit_price' => 1800.00],
                    ['id' => 'i-003-2', 'description' => 'Table Centrepiece (Floral+Acrylic)', 'delivery_date' => '2026-05-20', 'quantity' => 30, 'unit' => 'pcs', 'unit_price' => 95.00],
                    ['id' => 'i-003-3', 'description' => 'Stage Décor Package', 'delivery_date' => '2026-05-20', 'quantity' => 1, 'unit' => 'set', 'unit_price' => 4200.00],
                ],
                'total' => 10050.00,
                'source' => 'manual',
                'created_at' => '2026-04-22T14:00:00',
            ],
            [
                'id' => 'po-004',
                'po_number' => 'PO-2026-0097',
                'po_date' => '2026-05-05',
                'sla_date' => '2026-06-02',
                'client_name' => 'Universiti Malaya',
                'client_type' => 'Government',
                'category' => 'Trophies & Awards',
                'contact' => 'regis@um.edu.my',
                'your_ref' => null,
                'currency' => 'MYR',
                'payment_term' => 'full_on_completion',
                'deposit_percent' => 0,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-004-1', 'description' => 'Crystal Chancellor Award', 'delivery_date' => '2026-06-02', 'quantity' => 5, 'unit' => 'pcs', 'unit_price' => 680.00],
                    ['id' => 'i-004-2', 'description' => 'Wooden Plaque with Engraving', 'delivery_date' => '2026-06-02', 'quantity' => 120, 'unit' => 'pcs', 'unit_price' => 88.00],
                    ['id' => 'i-004-3', 'description' => 'Medal with Ribbon', 'delivery_date' => '2026-06-02', 'quantity' => 200, 'unit' => 'pcs', 'unit_price' => 25.00],
                ],
                'total' => 19960.00,
                'source' => 'manual',
                'created_at' => '2026-05-05T09:15:00',
            ],
            [
                'id' => 'po-005',
                'po_number' => 'PO-2026-0103',
                'po_date' => '2026-05-12',
                'sla_date' => '2026-06-09',
                'client_name' => 'Maybank Berhad',
                'client_type' => 'Private',
                'category' => 'Uniforms',
                'contact' => 'admin@maybank.com',
                'your_ref' => 'QT-204',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 30,
                'amount_paid' => 4200.00,
                'items' => [
                    ['id' => 'i-005-1', 'description' => 'Corporate Polo Shirt (Embroidered)', 'delivery_date' => '2026-06-09', 'quantity' => 200, 'unit' => 'pcs', 'unit_price' => 65.00],
                    ['id' => 'i-005-2', 'description' => 'Corporate Lanyard with ID Holder', 'delivery_date' => '2026-06-09', 'quantity' => 200, 'unit' => 'pcs', 'unit_price' => 7.00],
                ],
                'total' => 14400.00,
                'source' => 'manual',
                'created_at' => '2026-05-12T11:00:00',
            ],
            [
                'id' => 'po-006',
                'po_number' => 'PO-2026-0110',
                'po_date' => '2026-05-20',
                'sla_date' => '2026-06-17',
                'client_name' => 'Kementerian Kesihatan Malaysia',
                'client_type' => 'Government',
                'category' => 'Office Furnishing',
                'contact' => 'perolehan@moh.gov.my',
                'your_ref' => null,
                'currency' => 'MYR',
                'payment_term' => 'full_on_completion',
                'deposit_percent' => 0,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-006-1', 'description' => 'Ergonomic Office Chair', 'delivery_date' => '2026-06-17', 'quantity' => 50, 'unit' => 'unit', 'unit_price' => 480.00],
                    ['id' => 'i-006-2', 'description' => 'Height-Adjustable Standing Desk', 'delivery_date' => '2026-06-17', 'quantity' => 20, 'unit' => 'unit', 'unit_price' => 1200.00],
                    ['id' => 'i-006-3', 'description' => 'Delivery & Assembly', 'delivery_date' => '2026-06-17', 'quantity' => 1, 'unit' => 'set', 'unit_price' => 800.00],
                ],
                'total' => 49800.00,
                'source' => 'manual',
                'created_at' => '2026-05-20T08:45:00',
            ],
            [
                'id' => 'po-007',
                'po_number' => 'PO-2026-0118',
                'po_date' => '2026-06-02',
                'sla_date' => '2026-06-30',
                'client_name' => 'CIMB Bank Berhad',
                'client_type' => 'Private',
                'category' => 'Wooden Serveware',
                'contact' => 'gifts@cimb.com',
                'your_ref' => 'QT-211',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 50,
                'amount_paid' => 6250.00,
                'items' => [
                    ['id' => 'i-007-1', 'description' => 'Walnut Cheese Board (Engraved)', 'delivery_date' => '2026-06-30', 'quantity' => 100, 'unit' => 'pcs', 'unit_price' => 85.00],
                    ['id' => 'i-007-2', 'description' => 'Bamboo Gift Box Set', 'delivery_date' => '2026-06-30', 'quantity' => 50, 'unit' => 'pcs', 'unit_price' => 150.00],
                ],
                'total' => 16000.00,
                'source' => 'manual',
                'created_at' => '2026-06-02T13:30:00',
            ],
            [
                'id' => 'po-008',
                'po_number' => 'PO-2026-0124',
                'po_date' => '2026-06-10',
                'sla_date' => '2026-07-08',
                'client_name' => 'Tenaga Nasional Berhad',
                'client_type' => 'Government',
                'category' => 'Trophies & Awards',
                'contact' => 'corp.gifts@tnb.com.my',
                'your_ref' => null,
                'currency' => 'MYR',
                'payment_term' => 'full_on_completion',
                'deposit_percent' => 0,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-008-1', 'description' => 'Custom Acrylic Award Stand', 'delivery_date' => '2026-07-08', 'quantity' => 80, 'unit' => 'pcs', 'unit_price' => 145.00],
                    ['id' => 'i-008-2', 'description' => 'Long Service Certificate Frame', 'delivery_date' => '2026-07-08', 'quantity' => 80, 'unit' => 'pcs', 'unit_price' => 55.00],
                    ['id' => 'i-008-3', 'description' => 'Packaging & Delivery', 'delivery_date' => '2026-07-08', 'quantity' => 1, 'unit' => 'set', 'unit_price' => 400.00],
                ],
                'total' => 16400.00,
                'source' => 'manual',
                'created_at' => '2026-06-10T10:00:00',
            ],
            [
                'id' => 'po-009',
                'po_number' => 'PO-2026-0131',
                'po_date' => '2026-06-18',
                'sla_date' => '2026-07-16',
                'client_name' => 'Axiata Group Berhad',
                'client_type' => 'Private',
                'category' => 'Event Décor',
                'contact' => 'events@axiata.com',
                'your_ref' => 'QT-220',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 50,
                'amount_paid' => 11500.00,
                'items' => [
                    ['id' => 'i-009-1', 'description' => 'LED Neon Sign (Custom Text)', 'delivery_date' => '2026-07-16', 'quantity' => 4, 'unit' => 'pcs', 'unit_price' => 1800.00],
                    ['id' => 'i-009-2', 'description' => 'Step & Repeat Backdrop 3x3m', 'delivery_date' => '2026-07-16', 'quantity' => 3, 'unit' => 'pcs', 'unit_price' => 1200.00],
                    ['id' => 'i-009-3', 'description' => 'Decorative Plant Wall Panel', 'delivery_date' => '2026-07-16', 'quantity' => 6, 'unit' => 'pcs', 'unit_price' => 650.00],
                    ['id' => 'i-009-4', 'description' => 'Installation & Teardown', 'delivery_date' => '2026-07-16', 'quantity' => 1, 'unit' => 'set', 'unit_price' => 1900.00],
                ],
                'total' => 23800.00,
                'source' => 'manual',
                'created_at' => '2026-06-18T09:00:00',
            ],
            [
                'id' => 'po-010',
                'po_number' => 'PO-2026-0139',
                'po_date' => '2026-07-01',
                'sla_date' => '2026-07-29',
                'client_name' => 'RHB Bank Berhad',
                'client_type' => 'Private',
                'category' => 'Uniforms',
                'contact' => 'procurement@rhb.com.my',
                'your_ref' => 'QT-228',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 30,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-010-1', 'description' => 'Corporate Blazer (Custom Cut)', 'delivery_date' => '2026-07-29', 'quantity' => 50, 'unit' => 'pcs', 'unit_price' => 320.00],
                    ['id' => 'i-010-2', 'description' => 'Corporate Slacks', 'delivery_date' => '2026-07-29', 'quantity' => 50, 'unit' => 'pcs', 'unit_price' => 180.00],
                    ['id' => 'i-010-3', 'description' => 'Embroidered Name Badge', 'delivery_date' => '2026-07-29', 'quantity' => 50, 'unit' => 'pcs', 'unit_price' => 15.00],
                ],
                'total' => 25750.00,
                'source' => 'manual',
                'created_at' => '2026-07-01T14:00:00',
            ],
            [
                'id' => 'po-011',
                'po_number' => 'PO-2026-0145',
                'po_date' => '2026-07-08',
                'sla_date' => '2026-08-05',
                'client_name' => 'Jabatan Bomba dan Penyelamat Malaysia',
                'client_type' => 'Government',
                'category' => 'Engraved Signage',
                'contact' => 'logistik@bomba.gov.my',
                'your_ref' => null,
                'currency' => 'MYR',
                'payment_term' => 'full_on_completion',
                'deposit_percent' => 0,
                'amount_paid' => 12600.00,
                'items' => [
                    ['id' => 'i-011-1', 'description' => 'Photoluminescent Exit Sign', 'delivery_date' => '2026-08-05', 'quantity' => 60, 'unit' => 'pcs', 'unit_price' => 95.00],
                    ['id' => 'i-011-2', 'description' => 'Stainless Steel Room Identifier', 'delivery_date' => '2026-08-05', 'quantity' => 80, 'unit' => 'pcs', 'unit_price' => 110.00],
                    ['id' => 'i-011-3', 'description' => 'Custom Safety Notice Board', 'delivery_date' => '2026-08-05', 'quantity' => 10, 'unit' => 'unit', 'unit_price' => 250.00],
                ],
                'total' => 16900.00,
                'source' => 'manual',
                'created_at' => '2026-07-08T08:30:00',
            ],
            [
                'id' => 'po-012',
                'po_number' => 'PO-2026-0152',
                'po_date' => '2026-07-15',
                'sla_date' => '2026-08-12',
                'client_name' => 'Hong Leong Bank Berhad',
                'client_type' => 'Private',
                'category' => 'Wooden Serveware',
                'contact' => 'csr@hlb.com.my',
                'your_ref' => 'QT-237',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 50,
                'amount_paid' => 4500.00,
                'items' => [
                    ['id' => 'i-012-1', 'description' => 'Teak Wood Serving Tray (Engraved)', 'delivery_date' => '2026-08-12', 'quantity' => 60, 'unit' => 'pcs', 'unit_price' => 120.00],
                    ['id' => 'i-012-2', 'description' => 'Bamboo Coaster Set (6pcs)', 'delivery_date' => '2026-08-12', 'quantity' => 30, 'unit' => 'set', 'unit_price' => 60.00],
                ],
                'total' => 9000.00,
                'source' => 'manual',
                'created_at' => '2026-07-15T11:00:00',
            ],
            [
                'id' => 'po-013',
                'po_number' => 'PO-2026-0160',
                'po_date' => '2026-07-22',
                'sla_date' => '2026-08-19',
                'client_name' => 'Lembaga Hasil Dalam Negeri',
                'client_type' => 'Government',
                'category' => 'Office Furnishing',
                'contact' => 'perolehan@lhdn.gov.my',
                'your_ref' => null,
                'currency' => 'MYR',
                'payment_term' => 'full_on_completion',
                'deposit_percent' => 0,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-013-1', 'description' => 'Steel Filing Cabinet (4-drawer)', 'delivery_date' => '2026-08-19', 'quantity' => 30, 'unit' => 'unit', 'unit_price' => 560.00],
                    ['id' => 'i-013-2', 'description' => 'Whiteboard (120x240cm)', 'delivery_date' => '2026-08-19', 'quantity' => 15, 'unit' => 'unit', 'unit_price' => 380.00],
                    ['id' => 'i-013-3', 'description' => 'Delivery & Setup', 'delivery_date' => '2026-08-19', 'quantity' => 1, 'unit' => 'set', 'unit_price' => 600.00],
                ],
                'total' => 28500.00,
                'source' => 'manual',
                'created_at' => '2026-07-22T09:00:00',
            ],
            [
                'id' => 'po-014',
                'po_number' => 'PO-2026-0167',
                'po_date' => '2026-08-05',
                'sla_date' => '2026-09-02',
                'client_name' => 'Sunway Group',
                'client_type' => 'Private',
                'category' => 'Trophies & Awards',
                'contact' => 'events@sunway.com.my',
                'your_ref' => 'QT-245',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 50,
                'amount_paid' => 8750.00,
                'items' => [
                    ['id' => 'i-014-1', 'description' => 'Crystal Golf Trophy (Large)', 'delivery_date' => '2026-09-02', 'quantity' => 10, 'unit' => 'pcs', 'unit_price' => 450.00],
                    ['id' => 'i-014-2', 'description' => 'Silver Salver Plate', 'delivery_date' => '2026-09-02', 'quantity' => 30, 'unit' => 'pcs', 'unit_price' => 280.00],
                    ['id' => 'i-014-3', 'description' => 'Engraved Crystal Block', 'delivery_date' => '2026-09-02', 'quantity' => 20, 'unit' => 'pcs', 'unit_price' => 195.00],
                ],
                'total' => 16300.00,
                'source' => 'manual',
                'created_at' => '2026-08-05T10:00:00',
            ],
            [
                'id' => 'po-015',
                'po_number' => 'PO-2026-0174',
                'po_date' => '2026-08-18',
                'sla_date' => '2026-09-15',
                'client_name' => 'Suruhanjaya Komunikasi dan Multimedia Malaysia',
                'client_type' => 'Government',
                'category' => 'Event Décor',
                'contact' => 'event@mcmc.gov.my',
                'your_ref' => null,
                'currency' => 'MYR',
                'payment_term' => 'full_on_completion',
                'deposit_percent' => 0,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-015-1', 'description' => 'Pull-Up Banner (85x200cm)', 'delivery_date' => '2026-09-15', 'quantity' => 20, 'unit' => 'pcs', 'unit_price' => 120.00],
                    ['id' => 'i-015-2', 'description' => 'Table Skirting (Premium)', 'delivery_date' => '2026-09-15', 'quantity' => 15, 'unit' => 'pcs', 'unit_price' => 95.00],
                    ['id' => 'i-015-3', 'description' => 'Custom Photo Booth Frame 2x2m', 'delivery_date' => '2026-09-15', 'quantity' => 2, 'unit' => 'unit', 'unit_price' => 1800.00],
                ],
                'total' => 7425.00,
                'source' => 'manual',
                'created_at' => '2026-08-18T14:00:00',
            ],
            [
                'id' => 'po-016',
                'po_number' => 'PO-2026-0181',
                'po_date' => '2026-09-01',
                'sla_date' => '2026-09-29',
                'client_name' => 'IHH Healthcare Berhad',
                'client_type' => 'Private',
                'category' => 'Uniforms',
                'contact' => 'ops@ihh.com.my',
                'your_ref' => 'QT-256',
                'currency' => 'MYR',
                'payment_term' => 'deposit',
                'deposit_percent' => 50,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-016-1', 'description' => 'Medical Scrub Set (Custom Embroidered)', 'delivery_date' => '2026-09-29', 'quantity' => 300, 'unit' => 'set', 'unit_price' => 95.00],
                    ['id' => 'i-016-2', 'description' => 'Nurse Cap (Embroidered)', 'delivery_date' => '2026-09-29', 'quantity' => 150, 'unit' => 'pcs', 'unit_price' => 25.00],
                ],
                'total' => 32250.00,
                'source' => 'manual',
                'created_at' => '2026-09-01T09:00:00',
            ],
            [
                'id' => 'po-017',
                'po_number' => 'PO-2026-0188',
                'po_date' => '2026-09-10',
                'sla_date' => '2026-10-08',
                'client_name' => 'Perbadanan Putrajaya',
                'client_type' => 'Government',
                'category' => 'Engraved Signage',
                'contact' => 'harta@ppj.gov.my',
                'your_ref' => null,
                'currency' => 'MYR',
                'payment_term' => 'full_on_completion',
                'deposit_percent' => 0,
                'amount_paid' => 0,
                'items' => [
                    ['id' => 'i-017-1', 'description' => 'Bilingual Directory Signage Board', 'delivery_date' => '2026-10-08', 'quantity' => 25, 'unit' => 'unit', 'unit_price' => 680.00],
                    ['id' => 'i-017-2', 'description' => 'Bronze Commemorative Plaque', 'delivery_date' => '2026-10-08', 'quantity' => 5, 'unit' => 'pcs', 'unit_price' => 850.00],
                    ['id' => 'i-017-3', 'description' => 'Delivery & Installation (Putrajaya)', 'delivery_date' => '2026-10-08', 'quantity' => 1, 'unit' => 'set', 'unit_price' => 1200.00],
                ],
                'total' => 22450.00,
                'source' => 'manual',
                'created_at' => '2026-09-10T10:30:00',
            ],
        ];
    }
}
